### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by craiglondon** [ExplodingCabbage/sublime-gitignorer#19] opened 2016-04-08 15:36 UTC
reloading plugin Gitignored File Excluder.gitignore_plugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "gitignore_plugin in C:\Users\craig\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 229, in <module>
  File "gitignore_plugin in C:\Users\craig\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 35, in start
  File "gitignore_plugin in C:\Users\craig\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 32, in run
  File "gitignore_plugin in C:\Users\craig\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 65, in update_file_exclude_patterns
TypeError: 'NoneType' object is not iterable

**Comment by LeoIannacone** [comment] 2016-10-18 11:46
I confirm this

**Comment by ExplodingCabbage** [comment] 2016-11-26 16:08
Hopefully fixed by https://github.com/ExplodingCabbage/sublime-gitignorer/pull/20, although since I don't know how to reproduce this bug I can't confirm that the fix works.

**Closed** 2016-11-26 16:09 UTC
